[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Paskera",email = "craftsun@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "fastapi (>=0.127.0,<0.128.0)",
    "uvicorn[standard] (>=0.40.0,<0.41.0)",
    "websocket (>=0.2.1,<0.3.0)",
    "websockets (>=15.0.1,<16.0.0)"
]

[tool.poetry]
packages = [{include = "backend", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dev = "src.backend.main:main"